//TODO: Replace demo products
export const products = [
  {
    id: 1,
    name: "Wireless Headphone",
    price: 20,
    discount: 40,
    ratings: 4.5,
    reviews: 142,
    url: "product1.jpeg",
  },
  {
    id: 2,
    name: "Bluetooth Speaker",
    price: 35,
    discount: 25,
    ratings: 4.2,
    reviews: 98,
    url: "product1.jpeg",
  },
  {
    id: 3,
    name: "Gaming Mouse",
    price: 15,
    discount: 30,
    ratings: 4.6,
    reviews: 210,
    url: "product1.jpeg",
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    price: 55,
    discount: 20,
    ratings: 4.7,
    reviews: 340,
    url: "product1.jpeg",
  },
  {
    id: 5,
    name: "Smart Watch",
    price: 80,
    discount: 35,
    ratings: 4.3,
    reviews: 175,
    url: "product1.jpeg",
  },
  {
    id: 6,
    name: "USB-C Charger",
    price: 12,
    discount: 15,
    ratings: 3.1,
    reviews: 65,
    url: "product1.jpeg",
  },
  {
    id: 7,
    name: "Wireless Earbuds",
    price: 45,
    discount: 45,
    ratings: 4.4,
    reviews: 290,
    url: "product1.jpeg",
  },
  {
    id: 8,
    name: "Laptop Stand",
    price: 25,
    discount: 10,
    ratings: 4.0,
    reviews: 54,
    url: "product1.jpeg",
  },
  {
    id: 9,
    name: "Power Bank",
    price: 30,
    discount: 28,
    ratings: 4.6,
    reviews: 180,
    url: "product1.jpeg",
  },
  {
    id: 10,
    name: "Webcam HD",
    price: 40,
    discount: 22,
    ratings: 4.3,
    reviews: 102,
    url: "product1.jpeg",
  },
];
